### ISSUE TITLE
iOS/Androidで複数アプリを監視できるようにする

### ISSUE THREAD

**Issue by seriwb** [seriwb/reviewet#8]
こんな感じで設定できるようにしたい

```yml
appId:
  iOS:
    - 490217893
    - 284815942
  android:
    - com.google.android.googlequicksearchbox
    - com.apple.android.music
```
